### ISSUE TITLE
Payload optimization

### ISSUE THREAD

**Issue by 0x4007** [ubiquity-os-marketplace/command-ask#19]
This is an example of a diff q&a gone bad. Too much was sent to the model and it was rate limited. Below describes a dynamic strategy that should be simple to implement and should intelligently include only the most relevant changes. 

https://github.com/ubiquity-os-marketplace/text-conversation-rewards/pull/163#issuecomment-2439995967

**Comment by 0x4007** [comment]
Assign isn't working on pull linked i thought we fixed this @gentlementlegen

**Comment by gentlementlegen** [comment]
@0x4007 Seems to work: https://github.com/ubiquity-os-marketplace/text-conversation-rewards/issues/77#issuecomment-2439958186 might be another reason for this.

**Comment by 0x4007** [comment]
Could be the user configured privacy settings we discussed in another thread. We should throw a warning when we see the negative graphql response due to privacy settings.

**Comment by gentlementlegen** [comment]
I will check the logs for details, hopefully more information is given there so we can determine the cause programmatically and take action.

**Comment by gentlementlegen** [comment]
Logs of the start stop
![image](https://github.com/user-attachments/assets/902a5474-6133-44c2-af0b-3ba9994fcc53)

No POST was received meaning the event was never forwarded

Kernel logs
![image](https://github.com/user-attachments/assets/2b1cf0c8-f1bd-4ce2-8726-d8e821ea1a3c)

So it seems the `fetch` transport broke which is why it never got delivered. Seems tricky to reproduce, will have a look.
